### ISSUE TITLE
Enable mocking of loggers

### ISSUE THREAD

**Issue by piyushmor** [MicroUtils/kotlin-logging#102]
Currently we cannot mock the logger for a class. we should be able to mock this in some way.

**Comment by oshai** [comment]
I think the way to achieve that is with the actual framework.  Here is an example with log4j: http://www.bertschneider.de/2014/12/05/Mocking-Log4j-Logger/

**Comment by AlexandrosAlexiou** [comment]
Hello, the link you provided seems broken, do we have any other resource on how to mock the logger?

Thanks!

**Comment by oshai** [comment]
There are other examples like:
- https://dev.to/claudiohigashi/mocking-logger-in-java-with-mockito-51k8
- https://stackoverflow.com/questions/8948916/mocking-logger-and-loggerfactory-with-powermock-and-mockito
