### ISSUE TITLE
Assertion-based logger

### ISSUE THREAD

**Issue by jnorthrup** [MicroUtils/kotlin-logging#104]
I noticed the README has the word "performance".

I don't use loggers, but when I do, it's for debugging, and often relates to something with that word.

when -ea is not used, this is a very high performance logger.
 
public class log {
    /**
     * conditional debug output assert log(Object,[prefix[,suffix]])
     * 
     */
    public static void log(Object ob, String... prefixSuffix) {
        assert log$(ob, prefixSuffix);
    }

    /**
     * conditional debug output assert log(Object,[prefix[,suffix]])
     *
     * @param ob
     * @param prefixSuffix
     * @return
     */
    public static boolean log$(Object ob, String...prefixSuffix) {
        //[bla bla bla]
        return true;
    }
}

**Comment by oshai** [comment]
ok, thanks for pointing that out, but I don't think this is an issue related to this library.

**Comment by jnorthrup** [comment]
im going off the tagline you put on the front page...
Lightweight ###### ###### ### #####. # convenient ### performant logging 

I don't know that slf4j is any of those things however I do know that if your compiler strips out your debug logging, you can claim truthg in advertising above.
