### ISSUE TITLE
Versions?

### ISSUE THREAD

**Issue by rnentjes** [MicroUtils/kotlin-logging#109]
How are the version managed? The build file revers to 1.6.27 but the latest release is 1.7.9, how does this work?

Is the code in the github repo the latest? Recent changes only seem to apply to the documentation.

**Comment by oshai** [comment]
I publish releases manually and don't update versions in build.gradle. However the code in github is up to date. Recent changes are documentation and multiplatform.
The repo is maintained if you have any doubts, most development is around multi platforms and contributions are welcome.

**Comment by rnentjes** [comment]
Ok clear, thank you. 

The reason I was asking is that I was testing Kotlin 1.4-M1 and it needs all dependencies to be build against that version as well (to test new ir format).

I will create a pull request with the changes once I can confirm that it's working.
