### ISSUE TITLE
Logging in JSON format

### ISSUE THREAD

**Issue by mhajirnis** [MicroUtils/kotlin-logging#111]
We are using Kotlin-Sprint boot-Gradle stack to develop webapp and using [Kotlin-logging](https://github.com/MicroUtils/kotlin-logging)
We are required to output log in JSON format. With default settings, it splits every line in separate JSON block and makes it difficult to analyze the log
How can we override the default settings to output log in JSON?

**Comment by oshai** [comment]
It's up to the logging framework itself. By default spring boot uses [logback](http://logback.qos.ch/), so the place to look for is probably in it's documentation. I also recommend reading [this](https://www.marcobehler.com/guides/a-guide-to-logging-in-java) to get an overview on the responsibilities of each framework.

**Comment by oshai** [comment]
@mhajirnis can I close the issue?

**Comment by mhajirnis** [comment]
Yes. Thanks!
