### ISSUE TITLE
Missing markers for slf4j-ext functions

### ISSUE THREAD

**Issue by FrozenSync** [MicroUtils/kotlin-logging#113]
According to [the SLF4J documentation](http://www.slf4j.org/extensions.html), ENTRY and EXIT are also FLOW markers, and THROWING and CATCHING are also EXCEPTION markers. These seem to be missing in the current implementation.

**Comment by oshai** [comment]
Can you elaborate what's the effect or how it should be fixed?

**Comment by FrozenSync** [comment]
From what I understand, ENTRY and EXIT extend FLOW. Similarly, THROWING and CATCHING extend EXCEPTION. The pairs are usually part of the same configuration, so being able to target a parent marker leads to simpler configuration.

**Comment by oshai** [comment]
you can see here how we get them:
https://github.com/MicroUtils/kotlin-logging/blob/f438aa9fdf3da1c10234a3c556b7318271b3610b/src/jvmMain/kotlin/mu/internal/LocationAwareKLogger.kt#L18
It's configured by slf4j so I guess it should work as expected.

**Comment by FrozenSync** [comment]
Apologies for the lack of response. I'll try to reproduce the issue in a minimal example in the coming days and come back to you on this.

**Comment by oshai** [comment]
Closing it for now, @FrozenSync you are welcome to reopen with updates.
