### ISSUE TITLE
Android R8 seems to alter the tag name when companion object extends KLogging()

### ISSUE THREAD

**Issue by 1951FDG** [MicroUtils/kotlin-logging#115]
Hello,

Thanks for this library, I'm using it :)

I have a class MainActivity with a companion object that extends KLogging():

I noticed that the tag name changes when R8 is on:

When R8 is on: io.github.getsixtyfour.openpyn.`MainActivity$b`

When R8 is off: io.github.getsixtyfour.openpyn.`MainActivity`

Browsing the code I noticed that KLoggerNameResolver is responsible for unwrapping the companion class to the enclosing class, I am however uncertain if there is a bug in the implementation or if R8 is doing something funky of which I am unfamiliar with...

Thanks

**Comment by oshai** [comment]
It might be so. You can try the alternative syntax of file level field if that helps.
If you can add a project that reproduces it I can try to debug the issue.

**Comment by 1951FDG** [comment]
Sorry for the late reply, the issue occurs only when R8 is enabled. I have created a clean sample project that reproduces the issue in release build variant, I'm grateful if you can try to debug the issue.

https://github.com/1951FDG/MyApplicaton

**Comment by oshai** [comment]
@1951FDG Thanks, can you please add the steps to reproduce the issue in that repo?

**Comment by oshai** [comment]
@1951FDG I am still not sure what are the steps to reproduce the issue.

**Comment by 1951FDG** [comment]
Sorry for the delay again

1. Open Android Studio
2. Open repo folder in Android Studio
3. Go to Build > Select Build Variant...
4. Change Active Build Variant from debug to release
5. Go to Run > Run 'app' (use emulator or your android phone if you have one)

The GUI of the app will show a text field, which is set to the name of the logger, 

When active build is release build, the text field will show:
`com.example.myapplication.MainActivity$a`

When active build is debug build, the text field will show:
`com.example.myapplication.MainActivity`

The issue occurs in release build when R8 (shrinker in the Android build process) is on (minifyEnabled == true)

**Comment by oshai** [comment]
The minification process caused the companion object to have different characteristics than a usual Kotlin Companion object. Since we are using a fragile mechanism that uses reflection, it doesn't work for this case, and I am not sure it is worth allowing it as it might break other use cases.
Anyway, I suggest that you use the following configuration that should work for the release build:
```
companion object {
        private val logger = KotlinLogging.logger {}
}
```
Please let me know if that is good enough as a solution.

**Comment by 1951FDG** [comment]
Thanks, this works perfectly!

Maybe include this info in the documentation for Android devs...

**Comment by oshai** [comment]
Added it [here](https://github.com/MicroUtils/kotlin-logging/wiki#q-android-r8-seems-corrupting-the-logger-name-what-can-i-do) to the wiki.
