### ISSUE TITLE
Custom Logger

### ISSUE THREAD

**Issue by tuus-amicus** [MicroUtils/kotlin-logging#116]
Greetings! I wanna write custom Logger saving all capabilities of KLogger, but with custom logic inside, wrapping basic one.

I am creating logger with such code:

`private val log = KLogging.logger {}`

So, the Custom logger:
```
class CustomLogger(
        private val delegate: KLogger
) : Logger by delegate {
    fun customInfo(any: Any) {
        delegate.info { "Hello, github, there is $any" }
    }
}
```
So what i need to do to extend KLogger?

**Comment by oshai** [comment]
The easiest way to extend a logger is adding an extension method. Using delegate as above is also possible (if overriding methods is required). I think the class should implements KLogger itself like that:
```
class CustomLogger(
        private val delegate: KLogger
) : KLogger by delegate {
    fun customInfo(any: Any) {
        delegate.info { "Hello, github, there is $any" }
    }
}
```
In addition, in order to create such instance I think the easiest is extension method like that:
```
fun KLogger.toCustomrLogger() = CustomLogger(this)
```
And then using it like that:
```
private val log = KLogging.logger {}.toCustomrLogger()
```

**Comment by tuus-amicus** [comment]
> The easiest way to extend a logger is adding an extension method. Using delegate as above is also possible (if overriding methods is required). I think the class should implements KLogger itself like that:
> 
> ```
> class CustomLogger(
>         private val delegate: KLogger
> ) : KLogger by delegate {
>     fun customInfo(any: Any) {
>         delegate.info { "Hello, github, there is $any" }
>     }
> }
> ```
> 
> In addition, in order to create such instance I think the easiest is extension method like that:
> 
> ```
> fun KLogger.toCustomrLogger() = CustomLogger(this)
> ```
> 
> And then using it like that:
> 
> ```
> private val log = KLogging.logger {}.toCustomrLogger()
> ```

But what if i need to inject some Spring bean inside `CustomLogger`. The option with extension isn't enough.

**Comment by oshai** [comment]
I guess you have to provide it manually. The way from above to create a logger is sort of "static".

**Comment by tuus-amicus** [comment]
> I guess you have to provide it manually. The way from above to create a logger is sort of "static".

Not exactly what i supposed to achieve, but your example help me a bit. Thanks, closing the issue.
