### ISSUE TITLE
Too magic interface

### ISSUE THREAD

**Issue by vimmerru** [MicroUtils/kotlin-logging#117]
```
private val logger = KotlinLogging.logger {}

class Example {
    fun bar() {
        val world = "world"
        logger.info { "hello $world" }
    }
}
```

Seems logger performs some magic to binding logger to class. What if i have 2 classes in file?

```
private val logger = KotlinLogging.logger {}

class Example1 {
    fun bar() {
        val world = "world"
        logger.info { "hello $world" }
    }
}

class Example2 {
    fun bar() {
        val world = "world"
        logger.info { "hello $world" }
    }
}
```

How logger will be binded? Maybe there is better option with using of companion object?

**Comment by oshai** [comment]
Logger name is inferred from the name of the file. If you check the bytecode you'll see that file level declarations are placed in a class of the file name end with "Kt".
What I like about this way is that the logger name matches the file name so it's easy to find it, unlike if you have a logger for each separate class in the file.

If you prefer the latter it is possible to inherit `KLogging`. See the example in the usage wiki: https://github.com/MicroUtils/kotlin-logging/wiki#usage

**Comment by vimmerru** [comment]
@oshai It helps, i missed wiki link
