### ISSUE TITLE
Where does release 1.8.0.1 come from?

### ISSUE THREAD

**Issue by breucode** [MicroUtils/kotlin-logging#120]
According to maven central, the latest version of this library is 1.8.0.1, which was for example updated to Kotlin 1.3.72.

Where does this release come from? I don't see any link to the state of the repo.

**Comment by sne11ius** [comment]
> Where does this release come from? I don't see any link to the state of the repo.

Me would like to know too :D
Thanks for the project btw. Using it in nearly any serious kotlin project now.

**Comment by oshai** [comment]
I'm sorry for not updating the changelog just yet. This is part of integrating kotlin native as of this issue: https://github.com/MicroUtils/kotlin-logging/pull/119
We still have some problems but artifacts should be safe to use.

**Comment by napperley** [comment]
The Kotlin 1.3.72 update is required on the Kotlin Native side since Kotlin Native currently doesn't provide any backwards compatibility guarantees. However the upcoming Kotlin 1.4 release **might** resolve the backwards compatibility situation with Kotlin Native :pray: .

**Comment by oshai** [comment]
1.8.3 is now released.
