### ISSUE TITLE
Message formatted twice.

### ISSUE THREAD

**Issue by thorin0** [MicroUtils/kotlin-logging#132]
Test code:
```
import mu.KotlinLogging

private val logger = KotlinLogging.logger {}

fun main() {
    logger.info("Message: {}", "String with {} curly braces")
}
```
Expected output:
```
Message: String with {} curly braces
```
Actual output:
```
Message: String with String with {} curly braces curly braces
```

**Comment by oshai** [comment]
Can you please share more details: the version used, is it JVM/JS and do you use underlying framework for logging?
Ideally, a repo with reproduction will be best.

**Comment by thorin0** [comment]
It is JVM version with logback backend.
```
        <dependency>
            <groupId>io.github.microutils</groupId>
            <artifactId>kotlin-logging</artifactId>
            <version>1.8.3</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.1.9</version>
        </dependency>
```
For the first time, the message format is applied here:
https://github.com/MicroUtils/kotlin-logging/blob/d51e8683840cfc69a18636a9b774c7c88c242b64/src/jvmMain/kotlin/mu/internal/LocationAwareKLogger.kt#L200
For the second time, the message format is applied here:
https://github.com/qos-ch/logback/blob/bbc783e6d68482abe8e7dff0d06708175e971b91/logback-classic/src/main/java/ch/qos/logback/classic/spi/LoggingEvent.java#L314

**Comment by oshai** [comment]
Thanks for the details! I managed to reproduce it in a test, and going to create a fix for it soon.
