### ISSUE TITLE
By default logger.debug is disabled 

### ISSUE THREAD

**Issue by RajTabesto** [MicroUtils/kotlin-logging#159]
Hello Everyone,

I open this issue because I am not able to use the logger and it shows me that the debug logger level is not enabled. But in documentation I can't find how to enable it.

Please can you explain why it doesn't work by default ? then how to enable it ? 

 this is my configuration , in build.gradle

    implementation 'org.slf4j:slf4j-simple:1.7.29'
    implementation 'io.github.microutils:kotlin-logging:2.0.3'

in activity : 

import mu.KotlinLogging

    private var logger = KotlinLogging.logger {}
        if (logger.isDebugEnabled)
            logger.debug("it is enabled ")
        else
            Log.d("activity", "No it is not enabled ")

Thank you very much in advance

**Comment by oshai** [comment]
if you're using android you should add slf4j android instead of simple. see: https://github.com/MicroUtils/kotlin-logging-example-android/commit/f2aaa481868c4e19ad250d2a80fe120f283981cf

**Comment by RajTabesto** [comment]
Hello, 

Thank you for your feeback ! 
As you adviced me I added the dependency :
    implementation 'org.slf4j:slf4j-android:1.7.30'

instead of simple dependency 

With this new dependency I was able to show info log successfully but debug level still not working (above code still show me "No it is not enabled")

Please is there any possibility to enable it ?

**Comment by oshai** [comment]
so `Log.d` is working but `logger.debug` isn't? (try to print both)
From my understanding this is actually the same, so try to use `activity` as the logger name:
private var logger = KotlinLogging.logger("activity")

**Comment by RajTabesto** [comment]
I just tested this 
```
    private var logger = KotlinLogging.logger("activity")

    logger.debug { " Yes the test is working " }
```

Unfortunately, It stills not working, But I confirm you that logger.info works and Log.d (from util) work.

**Comment by oshai** [comment]
I think the issue is related to slf4j-android. See this question: https://stackoverflow.com/q/19984838/411965
Maybe one of the solutions can help.

**Comment by RajTabesto** [comment]
Thank you for your answer , I will check it

**Comment by mark-lapasa** [comment]
@RajTabesto 6 years later, there doesn't seem to be a workaround to get DEBUG to work as naturally as INFO and higher.

**Comment by mark-lapasa** [comment]
@RajTabesto @oshai Here is the fix I used to enable usage of logger.debug {} to work on Android:

```
// build.gradle (app)
dependencies {
    implementation 'io.github.microutils:kotlin-logging:1.12.0'
    implementation group: 'sk.baka.slf4j', name: 'slf4j-handroid', version: '1.7.30'
}

```

```
// MyApplicaion.kt
class MyApplicaion: Application() {
    init {
        HandroidLoggerAdapter.DEBUG = BuildConfig.DEBUG
    }
}
```

Credit to Martin Vysny's slf4j-handroid (a fork of slf4j-android) that allows programmatic access to explicitly set the default log level to something other than INFO and above.

_caveat emptor_

Read more about it here - https://jira.qos.ch/browse/SLF4J-314?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

**Comment by RajTabesto** [comment]
Hello @mark-lapasa, 

Thank you for your answer !  Yes I confirm you that your solution is working ! 
I am closing this issue .
