### ISSUE TITLE
Kotlin-logging version 1.12.0 is missing .module file in Maven artifact

### ISSUE THREAD

**Issue by checketts** [MicroUtils/kotlin-logging#163]
(This is as different from the `module` in #158 )

Around Gradle v5.3 an new metadata module was introduced (see https://docs.gradle.org/current/userguide/publishing_gradle_module_metadata.html#sub:disabling-gmm-publication)

version 2.0.4 is doing it correctly: see https://repo1.maven.org/maven2/io/github/microutils/kotlin-logging/2.0.4/

However the `.module` file is missing in the 1.x branch (see https://repo1.maven.org/maven2/io/github/microutils/kotlin-logging/1.12.0/)

However the 1.12.0 `pom.xml` includes a comment that indicates it had generated the metadata: 

```
<!--
 This module was also published with a richer model, Gradle metadata,  
-->
<!--
 which should be used instead. Do not delete the following line which  
-->
<!--
 is to indicate to Gradle or any Gradle module metadata file consumer  
-->
<!-- that they should prefer consuming it instead. -->
<!-- do_not_remove: published-with-gradle-metadata -->
```

That tells Gradle to check for that metadata.

## Proposal

Please consider uploading the missing `.module` files or [disabling that feature](https://docs.gradle.org/current/userguide/publishing_gradle_module_metadata.html#sub:disabling-gmm-publication).

Otherwise users that upgrade their version of Gradle won't be able to use the 1.x branch and will have to go to the 2.x version.

## Why aren't most people affected?

With the missing `.module` files, Maven central returns a 404 and Gradle recovers gracefully. However when using an internal/enterprise Maven repository, it is common for them to lock it down and configure it to return 403 status codes instead of 404. So in that case Gradle doesn't gracefully recover.

**Comment by oshai** [comment]
Thanks for the detailed report!
Since 1.x is in maintenance status it looks like a better approach will be disabling gmm.
You're welcome to create a PR, or I will do that soon.

**Comment by oshai** [comment]
Will release this in 1.12.1.

**Comment by breun** [comment]
After upgrading 1.12.0 to 1.12.1 my kotlin-logging imports no longer work.

IntelliJ is showing that it cannot find the `mu` package for this import for instance:

```
import mu.KLogging
```

And trying to run a build via Maven results in this:

```
[ERROR] /path/to/File.kt: (7, 11) Unresolved reference: KLogging
```

**Comment by checketts** [comment]
That sounds like a new issue. Make sure your dependency downloaded. Perhaps it just didn't download

**Comment by breun** [comment]
I created a new issue with a reproduction project: https://github.com/MicroUtils/kotlin-logging/issues/170

**Comment by oshai** [comment]
1.x is no longer supported, see #180. If this issue still happens in 2.x please reopen with details.
