### ISSUE TITLE
LOG4J2 binding fails when used within a Spring Boot application

### ISSUE THREAD

**Issue by colljos999** [MicroUtils/kotlin-logging#164]
I have successfully tested the **kotlin-logging** library with **log4j2** in a simple standalone Kotlin project using gradle as follows:

```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"

    // logging API
    implementation "io.github.microutils:kotlin-logging-jvm:2.0.4"
    runtimeOnly "org.apache.logging.log4j:log4j-slf4j18-impl:2.14.0"
}
```

However when I use the same configuration with a Spring Boot project I always get the following error at run-time (upon starting a Spring Boot application via its main):

```
DEBUG StatusLogger org.slf4j.helpers.Log4jLoggerFactory is not on classpath. Good!
DEBUG StatusLogger Using ShutdownCallbackRegistry class org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry
WARN StatusLogger Multiple logging implementations found: 
Factory: org.apache.logging.log4j.core.impl.Log4jContextFactory, Weighting: 10
Factory: org.apache.logging.slf4j.SLF4JLoggerContextFactory, Weighting: 15
Using factory: org.apache.logging.slf4j.SLF4JLoggerContextFactory
Exception in thread "main" org.apache.logging.log4j.LoggingException: log4j-slf4j-impl cannot be present with log4j-to-slf4j
```

The last line is telling me clearly what the problem is, but how do I resolve this?
 **log4j-slf4j-impl cannot be present with log4j-to-slf4j**

**Notes:**
- I have configured Spring Boot to use LOG42J using in its application properties file:
`org.springframework.boot.logging.LoggingSystem=org.springframework.boot.logging.log4j2.Log4J2LoggingSystem`
as per https://docs.spring.io/spring-boot/docs/2.1.2.RELEASE/reference/html/boot-features-logging.html#boot-features-custom-log-configuration

- I have also excluded the default Spring Logging libraries and run-time bindings in my build.gradle file as follows:

```
    configurations {
        runtime {
            // We want to use SLF4J's version of these bindings: log4j-slf4j-impl
            // Remove any transitive dependency on Apache's version (used by Spring Boot)
            exclude group: 'commons-logging', module: 'commons-logging'
            // Remove any transitive dependency on Logback
            exclude group: 'ch.qos.logback'
        }
    }
```

**Comment by oshai** [comment]
The issue is not related to kotlin-logging, but probably to spring boot. see: https://stackoverflow.com/a/59667631/411965

**Comment by oshai** [comment]
closing this as stale. if you have more info to provide please reopen.
