### ISSUE TITLE
How can I get the actual logger for testing purposes?

### ISSUE THREAD

**Issue by Zordid** [MicroUtils/kotlin-logging#171]
Cannot figure this one out:

To test the logging of a product, I want to use slf4j-test. This one requires to get the actual logger like so:

`val logger: TestLogger = TestLoggerFactory.getTestLogger(MySpecialClass::class.java)`

The problem is: when using kotlin-logging, I create my logger this way:

MySpecialClass.kt:
```
private val logger = mu.KotlinLogging.logger {}

class MySpecialClass {
...
}
```

And as such, the logger "lives" in MySpecialClassKt - the hidden Java class Kotlin creates automatically behind the scenes.

I tried this, of course:
`val logger: TestLogger = TestLoggerFactory.getTestLogger(MySpecialClassKt::class.java)`

But Kotlin does not allow me to even see the ...Kt class!

How can I get to the logger that has been created using kotlin-logging?

Thanks!

**Comment by oshai** [comment]
Try this:
```
private val logger = mu.KotlinLogging.logger(TestLoggerFactory.getTestLogger(MySpecialClassKt::class.java))
```

**Comment by oshai** [comment]
Please reopen if still relevant.
