### ISSUE TITLE
Support optional/nullable values for MDC

### ISSUE THREAD

**Issue by fdw** [MicroUtils/kotlin-logging#172]
I'd like  to add a value to the `MDC` *if it exists*. With the current implementation, I have to manually check this before I can call `withLoggingContext`. However, I'd like to pass a nullable argument that is only added to `MDC` if it's not null.

If you're interested, I would also try to write a PR.

**Comment by oshai** [comment]
what kind of api did you have in mind?

**Comment by fdw** [comment]
My suggestion would be a very simple `fun withLoggingContext(vararg Pair<String, String?>...)` with a `filter { it.value != null}` or something similar.

**Comment by fdw** [comment]
It was so easy that I went ahead and opened a PR. Hope you don't mind :)

**Comment by oshai** [comment]
Released in 2.0.7. Thanks again!

**Comment by fdw** [comment]
Quick question: I can't find a 2.0.7 release. Did I misunderstand you?

**Comment by oshai** [comment]
I think it's because jcenter is not working anymore because the build was working: https://travis-ci.org/github/MicroUtils/kotlin-logging/jobs/761498773

I'll have to move to use maven central directly and only then publish again.

**Comment by fdw** [comment]
Ah, thank you and good luck! 🙂
