### ISSUE TITLE
Suggestion to use reified genertic fun instead of `KotlinLogging.logger`

### ISSUE THREAD

**Issue by kosiakk** [MicroUtils/kotlin-logging#179]
Option to use normal function call
```kotlin
val logger = KotlinLogging.logger()
```
instead of current
```kotlin
val logger = KotlinLogging.logger {}
```
or both (maybe with deprecation and automatic migration, if community agrees)

Definition of such function is a little bit unusual because it's defined as an extention to any class:

```kotlin
inline fun <reified T> T.getLogger(): KLogger {
    val clazz = T::class.java
    val name = clazz.canonicalName ?: clazz.toString()
    return KotlinLogging.logger(name) // can be simplified with access to KLoggerFactory
}
```

I think this is better from any point of view: 
- usual syntax
- no guessing the class name by lambda class name
- the best possible performance (a bit important because logger is usually not static in Kotlin)

**Comment by kosiakk** [comment]
Since `T` is a `reified` type parameter, it's known at runtime.  Also the function is `inline`, so that generated byte-code has a simple class literal. This is a decompiled version of generated code:
```
      Class clazz$iv = GlobalSchedule.class;
      String var10001 = clazz$iv.getCanonicalName();
      if (var10001 == null) {
         var10001 = clazz$iv.toString();
         Intrinsics.checkNotNullExpressionValue(var10001, "clazz.toString()");
      }

      String name$iv = var10001;
      this.logger = KotlinLogging.INSTANCE.logger(name$iv);
```

**Comment by oshai** [comment]
Something is not 100% clear to me:
The signature is `KotlinLogging.logger()` although the method called `getLogger`?
In addition - isn't `T` resolved to `KotlinLogging` at runtime?

**Comment by kosiakk** [comment]
1. Yes, sorry `getLogger` is just how I called it locally - I've wrote this function for me, as external to Kotlin-logging. Internally you could choose different name and pass `Class` instance directly to SLF4J (they will deal with names)

2. Due to Java generic type erasure, it's impossible at runtime dymanically. So it's statically compiled to a specific class by means of Kotlin's [reified generic types](https://kotlinlang.org/docs/inline-functions.html#reified-type-parameters). Therefore `T` is not resolved. It's a sepecific constant for each method call, baked-in by the compiler at call-site.

**Comment by oshai** [comment]
ok, thanks. I suggest to create a PR to add such functionality.
We can discuss later if we want to deprecate other apis.

**Comment by ArcticLampyrid** [comment]
> In addition - isn't `T` resolved to `KotlinLogging` at runtime?

IMO, the api is used in following way:
```kotlin
val x = UserClass1()
x.getLogger()
```

For those which has a `this` context, just `getLogger().xxx(......)`
more detailed:
```kotlin
class UserClass1(){
    val logger = getLogger() // `this` points to a `UserClass1` instance so `T` points to `UserClass1`
}
```

**Comment by severn-everett** [comment]
I experimented with an implementation of this in PR #205, and it doesn't look feasible for a couple of reasons:
1. KotlinJS does not permit the `qualifiedName` function, so all that's available for a class object is `simpleName`, which is just going to produce "function".
2. It'd be easy to use in the wrong way. The inline function will have to be imported statically and called without the `KotlinLogging` qualifier, e.g.
```
import mu.KotlinLogging.getLogger

class Foo {
    val logger = getLogger()
}
```
If it's called via
```
class Foo {
    val logger = KotlinLogging.getLogger()
}
```
it'll instantiate a logger for `KotlinLogging`.
3. Kotlin does not permit inline functions with reified generics at the file level, so this is not possible:
```
import mu.KotlinLogging.getLogger

val logger = getLogger()

class Foo
```

**Comment by oshai** [comment]
@severn-everett thanks for your effort! closing this issue for now as not feasable.
