### ISSUE TITLE
performance problem: logger.*(lambda) are not inlined

### ISSUE THREAD

**Issue by cvmocanu** [MicroUtils/kotlin-logging#18]
### Problem
The logger.info/debug/error/etc. calls that take a lambda should be inlined.
Otherwise we replace the creation of one object (e.g. a StringBuilder) with the creation of another object (the lambda instance), which in time will put unnecessary pressure on the garbage collector.

Decompile a class that has logger.*(lambda) calls to see the problem. The [procyon decompiler](https://bitbucket.org/mstrobel/procyon/wiki/Java%20Decompiler) works ok for this case, though sometimes it chokes on Kotlin compiled bytecode.

I wanted to fix this myself and create a pull request, but these calls are inside an interface (``KLogger``) and functions inside interfaces cannot be inlined. This probably means that fixing this issue will result in breaking the existing API. Since it's your call if you want to break the backwards compatibility (and in what way), I didn't do it.

### Idea for solution
Here is an idea for the solution:
```kotlin
import org.slf4j.Logger
import org.slf4j.LoggerFactory

fun main(args: Array<String>) {
    App().sayHi("World")
}

class App {

    companion object {
        private val logger = KInlineLogger.create()
    }

    fun sayHi(name: String) {
        logger.info { "Hello $name!" }
    }
}

class KInlineLogger private constructor(val wrappedLogger: Logger): Logger by wrappedLogger  {

    companion object {
        private val kInlineLoggerFqn = KInlineLogger::class.java.name

        fun create(): KInlineLogger {
            return KInlineLogger(
                    LoggerFactory.getLogger(
                            findLoggerName()
                    )
            )
        }

        private fun findLoggerName(): String {
            val exception = Exception()

            return exception.stackTrace
                    .map { it.className }
                    .filter { it != kInlineLoggerFqn }       // exclude self
                    .filter { !it.endsWith("\$Companion") }  // exclude self companion & any other companions (if the KInlineLogger is declared inside a companion object)
                    .first()
        }
    }

    inline fun info(messageBlock: () -> Any) {
        if (wrappedLogger.isInfoEnabled) {
            wrappedLogger.info(messageBlock.invoke().toString())
        }
    }

}
```

The ``App.sayHi`` method compiles to:
```java
public final void sayHi(@NotNull final String name) {
    Intrinsics.checkParameterIsNotNull((Object)name, "name");
    final KInlineLogger this_$iv = App.Companion.getLogger();
    if (this_$iv.getWrappedLogger().isInfoEnabled()) {
        this_$iv.getWrappedLogger().info(("Hello " + name + "!").toString());
    }
}
```
Which is how we would optimize it manually.

Without inlining the ``info`` method though, a lambda instance is created (to capture the ``name``):
```java
public final void sayHi(@NotNull final String name) {
    Intrinsics.checkParameterIsNotNull((Object)name, "name");
    App.Companion.getLogger().info((Function0<?>)new App$sayHi.App$sayHi$1(name));
}
```
Notice how the lambda is instantiated, creating an unnecessary object, that the garbage collector has to clean.
A new object will be created for each log statement that needs to capture some variables.

In addition to this the call to the constructor and the dispatch to lambda.invoke is not free. It probably takes very little time, but it's unnecessary.

**Comment by oshai** [comment]
Thanks for your report. It was like that before, the main problem is with LocationAwareLogger - inlined methods cause it to show incorrect line numbers on the log messages. I hope in the future labmda expresssion will be optimized to create such overhead. let me know what you think about that.

**Comment by smichel17** [comment]
If anyone is interested, I combined code from this and Anko to make a really trimmed down logger that:

- Drops location-aware support and inlines everything
- Drops the slf4j dependency and just uses android.util.Log
- Adds an optional `enabled: Boolean` param to the Logger class (the one that your companion object will extend) to disable/enable logging on a class-by-class basis. If omitted it'll just default to whatever's defined in the logging file.
- Destroys several of the nice abstractions and crams everything into one file, because I'm a terrible person.
- Drops the tests because I'm lazy. Planning to re-add at some point.

Currently living [here](https://github.com/raatmarien/red-moon/blob/master/app/src/main/java/com/jmstudios/redmoon/util/Logger.kt), might split it out into a separate lib at some point.
