### ISSUE TITLE
Deprecate 1.x support

### ISSUE THREAD

**Issue by oshai** [MicroUtils/kotlin-logging#180]
Version 2.x released last September, more than half year ago.
I would like to stop supporting and deprecate version 1.x, mostly since the move out of jcenter might complicate back-porting of releases.

I wanted to know if there are any objections or concerns. 
If not, I will not fix more bugs to that version and write it on the readme.

**Comment by sharmando** [comment]
Additionally there seems to be a lot of releases on 2.x that are not in 1.x. The comment about still recommending 1.x for jvm lib users seems misleading.

**Comment by oshai** [comment]
will not support 1.x anymore.
