### ISSUE TITLE
Make kotlin stdlib dependencies "provided" (runtimeOnly) 

### ISSUE THREAD

**Issue by apatrida** [MicroUtils/kotlin-logging#181]
There is no reason for the library (outside of your own testing) to include the Kotlin stdlib dependencies as impleemntation/api, but they should be runtimeOnly to not interfere with whatever the calling application is using.

**Comment by oshai** [comment]
Can you please give more details why you think it should be like that or what does it solves?
IIUC provided means lib users runtime will provide the dependency. At least theoretically someone can use the lib from Java without other kotlin deps and it will fail.

**Comment by oshai** [comment]
I didn't find any reference that recommends this. The only thing I found is: https://kotlinlang.org/docs/whatsnew14.html#dependency-on-the-standard-library-added-by-default

I am closing this issue. Please reopen if you have more details.
