### ISSUE TITLE
Put LICENSE to the JAR

### ISSUE THREAD

**Issue by bespaltovyj** [MicroUtils/kotlin-logging#188]
I use [gradle plugin](https://github.com/jk1/Gradle-License-Report) for automatic check dependencies licenses. But your library not verified, because in your jar file license not present.
 Can you put license to JAR file?
![image](https://user-images.githubusercontent.com/32296746/129609807-ab6ebe78-199a-45ea-84e1-539b85476301.png)

**Comment by oshai** [comment]
Hi, thanks for reporting the issue!
I am not aware of any standard of adding the license file to the jar. Can you point out such?
Maybe a better idea will be that the gradle plugin will look also on github to check for license file?

**Comment by BorzdeG** [comment]
https://github.com/merkle-open/gradle-license-enforce-plugin fetches information from Maven POM file

**Comment by bespaltovyj** [comment]
>I am not aware of any standard of adding the license file to the jar. Can you point out such?

I'm not good at software licensing, but in [apache license page](https://www.apache.org/licenses/LICENSE-2.0) 
"Include a copy of the Apache License, typically in a file called LICENSE, in your work"

Distributing source code and binary files are two different things and in both cases you need a license file(in source code is present). Most likely, the licenses in maven pom refer only to the maven repository and the correct check is checking the license file. But I`m not suer whether it is necessary to put the linece file  into the jar.

>https://github.com/merkle-open/gradle-license-enforce-plugin fetches information from Maven POM file

Thanks for link, I chose my plugin because it is more popular and I hope that its support will not be discontinued.

**Comment by oshai** [comment]
So it sounds like having it in the pom.xml is enough (and more standard).

**Comment by choweiyuan** [comment]
I use the same https://github.com/jk1/Gradle-License-Report plugin to check dependencies license and ran into the same problem. Interestingly this wasn't a problem back in v1.x.x, problem starts from v2 onwards

Either way would be good to have this fixed

**Comment by bespaltovyj** [comment]
I can fix this problem if the owners of the project don't mind.

**Comment by oshai** [comment]
sure, go ahead and send a PR.

**Comment by bespaltovyj** [comment]
The problem turned out to be more complicated than I expected.
And the main reason is that `kotlin-logging` jar is a kotlin multiplatform jar. And the [plugin](https://github.com/jk1/Gradle-License-Report) can't read its licenses.

The solution to this problem is to change the type of dependency to `kotlin-logging-jvm`.
But I still did a [PR](https://github.com/MicroUtils/kotlin-logging/pull/191) with the addition of a license, because it seems right to me.

P.S. the [plugin](https://github.com/jk1/Gradle-License-Report) is able to process the license from the POM.

**Comment by oshai** [comment]
solved in #191 version `2.0.12`.
