### ISSUE TITLE
move from travis to github actions

### ISSUE THREAD

**Issue by oshai** [MicroUtils/kotlin-logging#198]

**Comment by oshai** [comment]
For build and release actions reference I used https://github.com/mpetuska/template-kmp-library/blob/master/.github/workflows/release.yml

**Comment by oshai** [comment]
see also: https://medium.com/kodein-koders/building-kotlin-multiplatform-with-github-actions-2478801d6d46

**Comment by BorzdeG** [comment]
for the "Validate Gradle wrapper" task you can use https://github.com/gradle/gradle-build-action

**Comment by oshai** [comment]
ended up publish from macoss to all platforms. see release `2.1.15`.
