### ISSUE TITLE
How to set project loglevel

### ISSUE THREAD

**Issue by hugadams** [MicroUtils/kotlin-logging#20]
Hi,

Thanks for putting this library together.  In using kotlin, I was putoff by the long/complex answers to the simple question "how do you log in kotlin (http://stackoverflow.com/questions/34416869/idiomatic-way-of-logging-in-kotlin)".

I'm using Klogging as follows:

        companion object: KLogging()

         init {
            logger.info("NewsArticle initialized: " + this)
          }

This works nicely, but when I do `logger.debug`, my IntelliJ IDEA run console doesn't show any output.  Do you know how I could set the console logger to debug or trace levels?  Is this an IDE setting, or can it be set in the call to `KLogging()`?

**Comment by oshai** [comment]
I saw a similar question on SO: http://stackoverflow.com/questions/43146977/how-to-configure-kotlin-logging-logger
Let me know if that clear things.

**Comment by oshai** [comment]
updated the frequently asked questions

**Comment by sschuberth** [comment]
Despite the FAQ entry I believe we desperately need a concrete example on how to set the log level when using e.g. logback as the logger implementation. I have in `build.gradle`:

    dependencies {
        // Use logback-classic as the logger for kotlin-logging / slf4j as it allow changing the log level at runtime.
        compile 'io.github.microutils:kotlin-logging:1.4.5'
        compile 'ch.qos.logback:logback-classic:1.2.3'
    }

And in my `main.kt`:

    internal val log = KotlinLogging.logger {}

    // ...

        if (!debug) {
            // Logback's default log level is DEBUG, so change that to INFO unless --debug is given.
            (log as ch.qos.logback.classic.Logger).level = ch.qos.logback.classic.Level.INFO
        }

But that gives

    Exception in thread "main" java.lang.ClassCastException: mu.internal.LocationAwareKLogger cannot be cast to ch.qos.logback.classic.Logger

So how am I supposed to access the logger implementation via kotlin-logging in order to call the logger implementation-specific code to set the log level?

**Comment by oshai** [comment]
Can you try to do it without the casting?

**Comment by oshai** [comment]
I think I understand the issue you mention. What I suggest is to add to the KLogger interface a method - getUnderlyingLogger() or something similar that will provide the underlying log implementation which can be casted to ch.qos.logback.classic.Logger in the case of logback. What do you think about this solution?

**Comment by sschuberth** [comment]
> getUnderlyingLogger() or something similar that will provide the underlying log implementation

That would probably work, although it seems a tad inconvenient. That is, slightly less convenient than being able to just casting the main class.

> Another alternative is to use xml configuration

But that does not seem to be usable if I need to change the log level at runtime triggered by external events (potentially multiple times).

**Comment by oshai** [comment]
I can add that, probably a property `underlyingLogger` is more appropriate. will you use that if such exists?

**Comment by sschuberth** [comment]
> will you use that if such exists?

Well, given that I just migrated to slf4k because of that missing feature, probably not right away, but I'll certainly give it a try in one of my next projects.

**Comment by oshai** [comment]
ok, I will add that to 1.4.6.

**Comment by oshai** [comment]
1.4.6 released

**Comment by ObserverOfTime** [comment]
This works although it's not ideal:
```kotlin
import ch.qos.logback.classic.Level
import ch.qos.logback.classic.Logger
import org.slf4j.LoggerFactory.getLogger

var org.slf4j.Logger.level
    get() = (getLogger(name) as Logger).level
    set(value) { (getLogger(name) as Logger).level = value }

logger.level = Level.DEBUG
```

**Comment by mipastgt** [comment]
This is already an old thread but the topic fits my question. How do you set the log level for the non-JVM targets. What is the underlying logger in that case? I am specifically asking for iOS and wasmJs.

**Comment by oshai** [comment]
> This is already an old thread but the topic fits my question. How do you set the log level for the non-JVM targets. What is the underlying logger in that case? I am specifically asking for iOS and wasmJs.

See: https://github.com/oshai/kotlin-logging/wiki/Multiplatform-support

**Comment by mipastgt** [comment]
Via your link I finally found the solution but the description in there is wrong.
Instead of
`KotlinLoggingConfiguration.LOG_LEVEL = KotlinLoggingLevel.DEBUG`
it must be
`KotlinLoggingConfiguration.logLevel = Level.DEBUG`
Maybe you can fix the documentation but many thanks for the hint and the tool anyway. I like it.

**Comment by oshai** [comment]
I updated the wiki.

**Comment by sharpau** [comment]
Hi, the wiki sent me here. I'm working on upgrading a fairly old version of KotlinLogging to the latest. It seems `KLogger` no longer implements `Logger`, and `underlyingLogger` is no longer available on `KLogger` as the wiki advises. Is there a straightforward solution to either of these problems?

**Comment by oshai** [comment]
> Hi, the wiki sent me here. I'm working on upgrading a fairly old version of KotlinLogging to the latest. It seems `KLogger` no longer implements `Logger`, and `underlyingLogger` is no longer available on `KLogger` as the wiki advises. Is there a straightforward solution to either of these problems?

There is now another interface `DelegatingKLogger`. So if the actual `KLogger` also implements `DelegatingKLogger`, `DelegatingKLogger.underlyingLogger` can be used.

Let me know where you saw this issue in the wiki, and I will update there.

**Comment by sharpau** [comment]
Thanks, I did end up doing that. As far as I can tell, for `kotlinlogging-jvm`, `DelegatingKLogger` is always the implementation used? I assume the reason it's no longer on `KLogger` is multiplatform support? It's a bit sad to have to add these extra casts everywhere when I know the loggers I'm using are always slf4j-based.

The wiki references it here: https://github.com/oshai/kotlin-logging/wiki#getting-the-actual-logger

**Comment by oshai** [comment]
> Thanks, I did end up doing that. As far as I can tell, for `kotlinlogging-jvm`, `DelegatingKLogger` is always the implementation used? I assume the reason it's no longer on `KLogger` is multiplatform support? It's a bit sad to have to add these extra casts everywhere when I know the loggers I'm using are always slf4j-based.
> 
> The wiki references it here: https://github.com/oshai/kotlin-logging/wiki#getting-the-actual-logger

I updated the wiki. Thinking about it now, I think I can have logger reference itself as underlying logger in direct platforms. This will prevent the cast.

**Comment by sharpau** [comment]
Thanks, the wiki update looks good and preventing the cast would be even better!
