### ISSUE TITLE
Global Log Level consitency 

### ISSUE THREAD

**Issue by set321go** [MicroUtils/kotlin-logging#200]
I'm having some issues with setting the log level globally within my app. I'm using kotlin js in a node env with IR turned on. My current understanding that the only way to override the default level is to use something like this

```
private val logger = KotlinLogging.logger {
    LOG_LEVEL = KotlinLoggingLevel.DEBUG
}
```
Is this correct?

The problem i'm having is that some loggers are initialized before this line in the compiled js files so they don't pickup the modified log level. These files also come from a dependency so it doesn't make sense to set the log level in those classes directly.

My current workaround is to go into the compiled js and replace the default value in the KotlinLoggingConfiguration with the one I want.

I don't need to be able to dynamically change the log level but I at least want to be able to set it for all of the loggers in my app. Probably this needs to be via something external that is loaded by the logger. Config File, env var, property etc.

**Comment by oshai** [comment]
Hi,
There is the js global configuration:
```
KotlinLoggingConfiguration.LOG_LEVEL = KotlinLoggingLevel.DEBUG
```
Is this what you're looking for?
More details on the [wiki](https://github.com/MicroUtils/kotlin-logging/wiki/Multiplatform-support#js-usage).

**Comment by set321go** [comment]
Yes thats what i was looking for thanks. Sorry for taking your time I missed that line in the wiki

**Comment by oshai** [comment]
NP

**Comment by Giuliopime** [comment]
> Hi, There is the js global configuration:
> 
> ```
> KotlinLoggingConfiguration.LOG_LEVEL = KotlinLoggingLevel.DEBUG
> ```
> 
> Is this what you're looking for? More details on the [wiki](https://github.com/MicroUtils/kotlin-logging/wiki/Multiplatform-support#js-usage).

Is there the same thing but for just the jvm lib?
Like being able to disable / enable debug logs globally in a project
