### ISSUE TITLE
Apache Log4j Security Vulnerabilities

### ISSUE THREAD

**Issue by apb-kawaguchi-kazuki** [MicroUtils/kotlin-logging#206]
i want to know about necessity of update this library version update.

found log4j version v2.14.1 for this library.
this version is under vulnerabilities.
but it only use in **jvmTest**.
https://github.com/MicroUtils/kotlin-logging/blob/master/build.gradle.kts

 I'm sorry, but i cant judge necessity of this Vulnerability affects for service.
sorry for my poor English.

▼official
https://logging.apache.org/log4j/2.x/security.html

**Comment by oshai** [comment]
fixed in #207 - and anyway since this is just used in tests, there isn't a real risk for users.

**Comment by oshai** [comment]
Some more background on the issue, copied from #207. 

`kotlin-logging` is a facade (similar to slf4j) means it only wraps the implementation you choose as a logging framework. 
 Popular implementations are logback and log4j.
On the tests of kotlin-logging we needed an actual implementation to use. We could write our own mocks but it makes more sense to take an actual impl for that to reflect how users use the lib. So kotlin-logging depends on log4j for testing only. 
Example of such tests can be seen [here](https://github.com/MicroUtils/kotlin-logging/blob/master/src/jvmTest/kotlin/mu/LoggingWithLocationTest.kt).
You can see the dependency [here](https://github.com/MicroUtils/kotlin-logging/blob/981daeae64780405092dab2420d4df342e01342b/build.gradle.kts#L71):
![image](https://user-images.githubusercontent.com/2683969/145766484-0e21f5a6-b138-4a32-a17f-e74213f1a538.png)

It means that this dependency does not pass transitively to users of kotlin-logging, and therfore users don't need to upgrade kotlin-logging itself. You can also see that in the [pom](https://repo1.maven.org/maven2/io/github/microutils/kotlin-logging-jvm/2.1.15/kotlin-logging-jvm-2.1.15.pom) that is generated for kotlin-logging.  
For people to feel more safe and for our own safety (when running tests) we upgraded kotlin-logging dependency on log4j.  
So it's not really needed, but I will not stop you from upgrading.

Hope that clears things a bit more.
