### ISSUE TITLE
Log4j has a serious vulnerability. use kotlin-logging:1.12.5

### ISSUE THREAD

**Issue by edgelv34** [MicroUtils/kotlin-logging#210]
Log4j has a serious vulnerability.

Currently, the kotlin version I can use is 1.4.32.

Therefore, use KLogger by adding "io.github" microutils:kotlin-logging:1.12.5' to the dependency.

Verified that the version that resolves the serious vulnerability in Log4j is kotlin-logging 2.1.16 and is available only in kotlin 1.6.0 and higher.

Is there any way to deal with the vulnerability of Log4j in the previous version?

**Comment by severn-everett** [comment]
I was under the impression that 2.1.16 is still usable by Kotlin 1.4, given the declaration of the 1.4 API version in the Gradle file:
```
kotlin {
    explicitApi()
    jvm {
        compilations.all {
            // kotlin compiler compatibility options
            kotlinOptions {
                apiVersion = "1.4"
                languageVersion = "1.4"
                jvmTarget = "1.8"
            }
        }
    }
```
@oshai Is this correct?

**Comment by evmetatron** [comment]
https://github.com/MicroUtils/kotlin-logging/pull/211

**Comment by oshai** [comment]
> I was under the impression that 2.1.16 is still usable by Kotlin 1.4, given the declaration of the 1.4 API version in the Gradle file:
> 
> ```
> kotlin {
>     explicitApi()
>     jvm {
>         compilations.all {
>             // kotlin compiler compatibility options
>             kotlinOptions {
>                 apiVersion = "1.4"
>                 languageVersion = "1.4"
>                 jvmTarget = "1.8"
>             }
>         }
>     }
> ```
> 
> @oshai Is this correct?

to the best of my knowledge, yes.

**Comment by oshai** [comment]
To add more context 1.x is deprecates see #180.
In addition, as far as we know `kotlin-logging` is not vulnerable to the cve by itself (as long as you use fixed log4j version). 
See more details: https://github.com/MicroUtils/kotlin-logging/issues/206#issuecomment-992175291

**Comment by edgelv34** [comment]
thx guys.
i found out as you say that kotlin-logging was used only for jvmtest purposes.
