### ISSUE TITLE
Update log4j2 version 2.17.1

### ISSUE THREAD

**Issue by imsprathap** [MicroUtils/kotlin-logging#221]

**Comment by oshai** [comment]
would you be interested in creating a PR?

**Comment by imsprathap** [comment]
@oshai Sure, here it is https://github.com/MicroUtils/kotlin-logging/pull/222

**Comment by sschuberth** [comment]
So, this should be closed as the PR got merged, right?

**Comment by imsprathap** [comment]
Closing as this is resolved
