### ISSUE TITLE
Add `Automatic-Module-Name` manifest entry

### ISSUE THREAD

**Issue by ascopes** [MicroUtils/kotlin-logging#223]
On Java 9 or above, in projects using JPMS modules, Maven will currently raise the following warning due to `kotlin-logging` not having the `Automatic-Module-Name` manifest entry:

```
[WARNING] *****************************************************************************************************************************************************
[WARNING] * Required filename-based automodules detected: [kotlin-logging-jvm-2.1.21.jar]. Please don't publish this project to a public artifact repository! *
[WARNING] *****************************************************************************************************************************************************
```

Would it be possible to push a release that has this MANIFEST entry set explicitly to avoid this issue? This reduces the likelihood of things breaking if build settings change between versions for those who are using Kotlin within a modular Java application.

I am not very savvy on Gradle, which is why I haven't put a PR up myself for this, but the Maven equivalent of this fix would be just specifying the following when producing the JAR:

```xml
<archive>
  <manifestEntries>
    <Automatic-Module-Name>io.github.microutils.kotlinlogging</Automatic-Module-Name>
  </manifestEntries>
</archive>
```
or similar.

Thanks

**Comment by oshai** [comment]
I found an explanation how to do that here: https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_modular_auto

**Comment by oshai** [comment]
Add in 3.0.3. please let me know if the issue is resolved.

**Comment by ascopes** [comment]
Looks to be good to go. Thanks :)
