### ISSUE TITLE
Reword slf4j references in README

### ISSUE THREAD

**Issue by sschuberth** [MicroUtils/kotlin-logging#229]
The README refers to slf4j in several places, which reads as if kotlin-logging would work for the the JVM target only. But to my understanding Kotlin multi-platform support has been added some time ago. So it should be made more clear in the README that more targets than JVM are supported.

**Comment by oshai** [comment]
the wiki has this section: https://github.com/MicroUtils/kotlin-logging/wiki/Multiplatform-support

We can add a link to it on the readme.

**Comment by sschuberth** [comment]
> We can add a link to it on the readme.

Thanks for the offer, but my main point is not about *adding* more information, but *removing* outdated / wrong information. Having that link in addition to the slf4j references would be even more confusing, IMO.

**Comment by oshai** [comment]
Would you like to create a pr with the suggestion?

**Comment by sschuberth** [comment]
While the changes are probably not many lines of code, I'm quite uncertain which parts of the docs are still wanted to refer to slf4j (e.g. for historical reasons), and which not, so I'd rather leave this to someone familiar with the project.

**Comment by oshai** [comment]
Created PR #255 for it.

**Comment by sschuberth** [comment]
> Created PR #255 for it.

Thank you!
