### ISSUE TITLE
any plans on adding color?

### ISSUE THREAD

**Issue by jamesalbert** [MicroUtils/kotlin-logging#24]
just wondering

**Comment by oshai** [comment]
What do you mean?

**Comment by jamesalbert** [comment]
like being able to something like: `logger.error("message", color="red")`

**Comment by jamesalbert** [comment]
maybe it doesn't necessarily make the whole message that color, but just the `[main] ERROR` part. I'll check it out and take a stab at it if that's a thing you'd want to have in the project

**Comment by oshai** [comment]
Its possible to do it on the underlying logging framework. See example here:
https://stackoverflow.com/questions/7848325/making-a-log4j-console-appender-use-different-colors-for-different-threads

**Comment by jamesalbert** [comment]
oh nice, cool then thanks!
