### ISSUE TITLE
Fix the `Greetings / greeting (pull_request)` check

### ISSUE THREAD

**Issue by yeikel** [MicroUtils/kotlin-logging#249]
This check is currently failing and it adds noise for new pull requests

**Comment by oshai** [comment]
This is probably because of https://github.com/actions/first-interaction/issues/101 which is fixed now. Please verify.

**Comment by Bladez1753** [comment]
> https://raw.githubusercontent.com/tronprotocol/Documentation/master/images/Wallet_for_Android/查看相关信息/查看

**Comment by oshai** [comment]
fixed.
