### ISSUE TITLE
Enabled / disable debug globally in a project

### ISSUE THREAD

**Issue by Giuliopime** [MicroUtils/kotlin-logging#250]
Is it possible to enable and disable the logging level (like debug) globally in a project.
I've seen there is an option for the multiplatform dependency but can't find it in the standard jvm one.

**Comment by oshai** [comment]
On the jvm the way to achieve that is in the actual logging framework that you use: log4j, logback, etc'.

**Comment by Giuliopime** [comment]
Got it 👍🏼
