### ISSUE TITLE
Regarding 3.0.2

### ISSUE THREAD

**Issue by yeikel** [MicroUtils/kotlin-logging#252]
I just noticed that there is a 3.0.2 version in Maven central : https://search.maven.org/artifact/io.github.microutils/kotlin-logging/3.0.2/jar

But we don't have any release notes for it

Could you please clarify what is the difference between 3.0.1 and 3.0.2? I could not find any tag or information about it

**Comment by oshai** [comment]
There wasn't significant changes between 3.0.1 and 3.0.2.
