### ISSUE TITLE
Incorrect class version 55.0

### ISSUE THREAD

**Issue by gotson** [MicroUtils/kotlin-logging#257]
Hi,

version 3.0.3 has incorrect class version 55.0 instead of 52.0:

```
error: cannot access KLogger
    private static final mu.KLogger logger = null;
                           ^
  bad class file: .gradle/caches/modules-2/files-2.1/io.github.microutils/kotlin-logging-jvm/3.0.3/a22ed63df54739199d36b967812e50ea68bf3bab/kotlin-logging-jvm-3.0.3.jar(mu/KLogger.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

Seems like it could be because of 20046655ae0db0739b987ea4fbeb2a3f9366f304 or #251 ?

The README doesn't mention any minimum Java version requirement, and 3.0.0 works well on Java 8.

**Comment by oshai** [comment]
Yes, bumping the Java version as part of #251 was unintentional. I will fix it.

**Comment by gotson** [comment]
> Please make sure it works in 3.0.4 once it's available.

Thanks, i confirm it's back to Java 8 on the latest 3.0.4
