### ISSUE TITLE
update to android studio 3.0 logging can't work

### ISSUE THREAD

**Issue by SamPeng87** [MicroUtils/kotlin-logging#27]
can't see any logger to console

10-19 04:37:09.356 17905-17917/? I/art: Debugger is no longer active

10-19 04:37:10.507 17905-17905/ I/InstantRun: starting instant run server: is main process
10-19 04:37:10.546 17905-17905/ W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
10-19 04:37:10.547 17905-17905/ W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
10-19 04:37:10.547 17905-17905/ W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by oshai** [comment]
Were you able to solve it?
