### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by elect86** [MicroUtils/kotlin-logging#28]
Hi,

following the readme, I instantiated at top level [here](https://github.com/kotlin-graphics/assimp/blob/master/src/main/kotlin/assimp/assimp.kt#L7): `val logger = KotlinLogging.logger {}`

and then I use wherever I need it like: `logger.warn{ "omg" }`

But whenever I run some tests, I always get the following:

> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

why?

**Comment by oshai** [comment]
I think you are missing the actual logging implementation (from
readme): Important
note: kotlin-logging depends on slf4j-api. In runtime, it is also required
to depend on a logging implementation. More details here
<http://saltnlight5.blogspot.co.il/2013/08/how-to-configure-slf4j-with-different.html>
.

**Comment by elect86** [comment]
Uh, sorry I was blind..

Anyway, following that link, adding this `compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.25'` to Gradle seems working.

However now I get a lot of noise for something external to my program..

https://gist.github.com/elect86/e3a74336984f1354f448b9eae72b1bde

Any idea how could I solve?

**Comment by oshai** [comment]
I think it is not possible with slf4j simple, but with other frameworks
such as log4j you can filter messages. Note that warn messages usually
indicates a problem that might be better to solve.

**Comment by AlexCzar** [comment]
@elect86 slf4j-simple is just that - simple :) Try logback instead, it is pretty straight forward to configure and is the de-facto standard for slf4j impl: https://logback.qos.ch/manual/configuration.html

**Comment by elect86** [comment]
Hi Alex, 

thanks for the feedback, I'll take a look :)

**Comment by oshai** [comment]
I will close the issue now. Youre welcome to reopen if there is still an issue.
