### ISSUE TITLE
Kotlin 1.2.0 support

### ISSUE THREAD

**Issue by gasch** [MicroUtils/kotlin-logging#29]
In class "KLoggerNameResolver" the line
"import kotlin.reflect.companionObject" (this was deprecated anyway in Kotlin 1.1)
should change to 
"import kotlin.reflect.full.companionObject"

**Comment by oshai** [comment]
thanks! are you willing to submit a pull request?

**Comment by gasch** [comment]
Forget my complaint. Was using an outdated version.
Sorry for the noise!

/gas


--
lg, /ga

**Comment by oshai** [comment]
NP.
