### ISSUE TITLE
Support log config in yaml

### ISSUE THREAD

**Issue by Decker108** [MicroUtils/kotlin-logging#36]
This SO post details how to use yaml to configure log4j: https://stackoverflow.com/questions/28101903/what-is-a-sample-default-config-file-in-yaml-for-log4j2

It would be real nice to be able to use yaml instead of xml or properties-files for configuring klogging.

**Comment by oshai** [comment]
unlike log4j, kotlin-logging does not have a configuration. It is just a facade for log4j. So it is possible to use yaml with it as the post describes in case the backing logging system is log4j. Hope that clear the things.
