### ISSUE TITLE
Doesn't work out of the box

### ISSUE THREAD

**Issue by richardjharris** [MicroUtils/kotlin-logging#37]
I am authoring an android app and added the build.gradle `compile` line as told:

```    compile 'io.github.microutils:kotlin-logging:1.4.9'```

The logcat output when actually using my app:

```
03-10 23:28:59.090 25160-25160/? I/InstantRun: starting instant run server: is main process
03-10 23:28:59.150 25160-25160/? W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
03-10 23:28:59.150 25160-25160/? W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
03-10 23:28:59.150 25160-25160/? W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

I know that third-party libraries are not supposed to place a dependency on a slf4j implementation. But ideally the installation instructions should produce a working implementatation, even for Java/Kotlin/Android newbies.

Suggestion: tell users how to set up slf4j when using kotlin-logging.

**Comment by richardjharris** [comment]
For example, I fixed the problem by adding this extra line to 'build.gradle'

`    compile 'org.slf4j:slf4j-simple:1.6.1'`

**Comment by oshai** [comment]
There are (at least) two places to see an example how to do that:
- in downloads section there is a comment about dependencies: https://github.com/MicroUtils/kotlin-logging#download
- a specific example for android: https://github.com/MicroUtils/kotlin-logging-example-android

Let me know if that helps or you think something else is required.
