### ISSUE TITLE
add support for logging with limit for messages per minutes

### ISSUE THREAD

**Issue by oshai** [MicroUtils/kotlin-logging#4]

**Comment by oshai** [comment]
this can assist in preventing log spamming with many similar messages.

**Comment by IRus** [comment]
This is not responsibility of our library or even logger facade. I think messages throttling is responsibility of concrete appender. But this is logging, so you **should log every message**, because you don't want lost important stacktraces and errors.

**Comment by oshai** [comment]
I tend to agree. on the other hand it seems like a valuable feature. I will close it now and reconsider in case it will pop-up again.
