### ISSUE TITLE
Latest Versions Not Listed As Releases

### ISSUE THREAD

**Issue by flatiron32** [MicroUtils/kotlin-logging#41]
The latest versions of this library are not listed as releases in GitHub.

**Comment by oshai** [comment]
I added 1.5.4, thanks!

**Comment by flatiron32** [comment]
Thanks! Would be nice to have all the intermediate releases tagged and added also.

**Comment by oshai** [comment]
Its only 1.5.3 other versions are broken. In 1.5.3 there are no additional features.
