### ISSUE TITLE
Examples/documentation with custom message format and different loggging system

### ISSUE THREAD

**Issue by nikita-sheremet-java-developer** [MicroUtils/kotlin-logging#42]
Ok I have included this lib via maven dependency and what next?

1. What logging system it uses by default?
1. I have put `log4j.properties` file in resources folder which has no impact on logging. So additional dependencies for log4j should be added? What exactly?
1. The same question about logback
1. Could please provide a couple of maven project with different message format settings for different logging system? This would be the best to see exact examples.

**Comment by oshai** [comment]
1. There is no default log system.
2+3. Yes, you should add additional dependencies, see here an example: http://saltnlight5.blogspot.co.il/2013/08/how-to-configure-slf4j-with-different.html
4. I will add a wiki to give more details.

Let me know if that helps.

**Comment by nikita-sheremet-java-developer** [comment]
> Let me know if that helps.
yes it helped thanks
