### ISSUE TITLE
Support SLF4J Markers 

### ISSUE THREAD

**Issue by darioseidl** [MicroUtils/kotlin-logging#43]
The SLF4J [Logger](https://www.slf4j.org/api/org/slf4j/Logger.html) allows specifying a [Marker](https://www.slf4j.org/api/org/slf4j/Marker.html) for log messages, e.g.

```
log.debug(MARKER, msg)
```

It would be nice if the `KLogger` would support these too to be able to specify a marker when using a lambda for the message.

I'd be happy to submit a pull request :)

**Comment by darioseidl** [comment]
We use markers to conditionally trigger appenders, for example our `SMTPAppender` is triggered by  a `SEND_MAIL` marker.

I have an [implementation](https://github.com/darioseidl/kotlin-logging/tree/markers) ready. However, to make it multi platform I had to remove the Kotlin 1.0 compatibility from the JVM module to allow type aliases. Not sure if this is a problem?

The tests currently use Log4j 1.2 (with `slf4j-log4j12`), which doesn't support markers, so the tests just make sure the log output is unaffected. To test the presence of the markers, SLF4J or Log4J 2 would be needed.

**Comment by darioseidl** [comment]
> It's ok to use typealias, so please keep compatibility directive but change it to 1.1.

Okay, thanks.

> Regarding tests, I think a better approach if possible is to change al the tests use log4j2 so it will support markers. Is that makes sense? is it feasible?

Yes, I think so. I haven't worked with log4j2 before, but I guess it's very similar. I'll take a look ...

**Comment by darioseidl** [comment]
Hello, I've converted to tests to log4j2 now and submitted a [pull request](https://github.com/MicroUtils/kotlin-logging/pull/48) The programmatic configuration is a bit different, and null log messages are logged as `null` instead of an empty string now. Other than that, not much has changed.

**Comment by oshai** [comment]
closed with #48
