### ISSUE TITLE
Link to examples in tests is wrong in the "Obtaining a logger" section of the wiki home page

### ISSUE THREAD

**Issue by mikem** [MicroUtils/kotlin-logging#44]
There's a link to examples in the test directory at the end of [the "Obtaining a logger" section](https://github.com/MicroUtils/kotlin-logging/wiki#obtaining-a-logger) in the wiki. It's pointing to https://github.com/MicroUtils/kotlin-logging/tree/master/src/test/kotlin/mu which currently returns a 404 Not Found.

I believe the correct link should be https://github.com/MicroUtils/kotlin-logging/tree/master/kotlin-logging-jvm/src/test/kotlin/mu.

**Comment by oshai** [comment]
Thanks for reporting! I fixed it.
