### ISSUE TITLE
oddity with delegation of isDebugEnabled

### ISSUE THREAD

**Issue by whenceforth** [MicroUtils/kotlin-logging#50]
I have configured my underlying logger to debug log, but I'm not getting any output. 
I then error logged a look at the logger and the underlying logger. The underlying logger says debug is enabled, but when I ask the KotlinLogger about debug, it says it is not enabled.  

It's weird. I see in LocationIgnorantKLogger that it uses delegation to the underlying logger, but it doesn't seem to be working since the values differ.  

Any thoughts on this? 

```
logger.error { "logger.javaClass.simpleName = ${logger.javaClass.simpleName}" }
        logger.error { "logger.underlyingLogger.javaClass.simpleName = ${logger.underlyingLogger.javaClass.simpleName}" }
        logger.error { "logger.isDebugEnabled = ${logger.isDebugEnabled}" }
        logger.error { "logger.underlyingLogger.isDebugEnabled = ${logger.underlyingLogger.isDebugEnabled}" }
```
output:

```
ERROR: logger.javaClass.simpleName = LocationIgnorantKLogger
ERROR: logger.underlyingLogger.javaClass.simpleName = TinylogLogger
ERROR: logger.isDebugEnabled = false
ERROR: logger.underlyingLogger.isDebugEnabled = true
```

**Comment by oshai** [comment]
Can you please provide more details: versions, what is the underlying logger its configuration and ideally a small repo on github to reproduce it?

**Comment by oshai** [comment]
Is there any update on the issue?

**Comment by whenceforth** [comment]
I'm afraid I'm not going to be able to spend time following up on this.
