### ISSUE TITLE
Please add copyright notice

### ISSUE THREAD

**Issue by andreasmuellergin** [MicroUtils/kotlin-logging#52]
The project contains an Apache 2.0 license file, however, it does not follow the conditions and recommendation in the appendix of the license.

Packages are routinely rejected by the OSS legal offices because of missing or incomplete copyright information. So it would be great to include the copyright statement to avoid problems when using this framework. 

Apache 2 license conditions according to Github License summary
 License and copyright notice
 State changes

Thanks a lot.

**Comment by oshai** [comment]
Can you give an example how it should be, or ideally a pull request?

**Comment by andreasmuellergin** [comment]
According to the appendix "Copyright {yyyy} {name of copyright owner}" which is probably covered by
Copyright 2016-2018 The kotlin.logging framework contributors

**Comment by oshai** [comment]
@andreasmuellergin please see this PR and let me know if that is ok. if so I will merge that: https://github.com/MicroUtils/kotlin-logging/pull/53

**Comment by oshai** [comment]
Added it
