### ISSUE TITLE
[Question] How to use logger inside extension function?

### ISSUE THREAD

**Issue by kkocel** [MicroUtils/kotlin-logging#59]
I would like to know what is recommended way to use logger inside extenstion function. I want to get actual name of function passed to logger.

**Comment by oshai** [comment]
I think it should work (unless the function is `inline`) Can you provide a code sample that it is not working for reproduction?

**Comment by kkocel** [comment]
I just wonder where to put initialization block. Inside each extension function that will log anything?
In some sort of companion object? Named object?

Logging itself works - but I want to get relevant name from the context where it's created.

**Comment by oshai** [comment]
Are you talking about the name of the logger? If so then you probably can access it if its public and declared in hierarchy.

**Comment by oshai** [comment]
@kkocel can I close the issue?

**Comment by kkocel** [comment]
Hi, I think I wasn't clear in previous posts. Now I'll try to be more specific and provide examples :)

Let's say I have following extension function inside file `MyDomainObjectMapper.kt`:

   
      fun String.toMyClass(): MyClass {

        logger.debug { "Mapping class type [$this] to my class" }
        //...
      }
    
    // inside same file there couple of other extensions functions which are doing some logging as well

I use logger here and my question is - where to initialize such logger in a way that it will be able to obtain name of the class. And how to initialize such logger once so I won't need to to do it in every extension function.

**Comment by oshai** [comment]
I would keep all loggers in a map in the file, class as key logger as value. With lazy init and limit on size. However, I don't know your actual use case but usually logger should reflect the file the nessage was printed and not the class it is extending. Hope that helps.
