### ISSUE TITLE
[Question] Next release?

### ISSUE THREAD

**Issue by robertfmurdock** [MicroUtils/kotlin-logging#62]
I just discovered the JS log level issue in 1.6.10, and I can see its fixed in the repo... will a new release be cut soon that includes that change? The library looks great other then that issue! 💯

**Comment by robertfmurdock** [comment]
Just noticed the readme references a 1.6.22 version, that doesn't show up on the releases tab in github for some reason. I'll mark this as closed for now.

**Comment by oshai** [comment]
Latest released version is 1.6.23. Can you try it?

**Comment by robertfmurdock** [comment]
Sure thing - I tried it from 1.6.22 and it fixed the issue. Now, that said,
maybe there's something wrong with the releases / tags tab in github! :-D

**Comment by oshai** [comment]
I stopped releasing to github. I might tag it in next releases again.
