### ISSUE TITLE
convert project to new MPP format

### ISSUE THREAD

**Issue by oshai** [MicroUtils/kotlin-logging#64]
In kotlin 1.3 there is a new format for MPP projects. we need to convert to that format.

**Comment by amcghie** [comment]
Were you also thinking about moving tothe Gradle Kotlin DSL as part of this change?

**Comment by oshai** [comment]
initially not, but I am open to that change as well. Last time I checked, it was not mature enough.

**Comment by oshai** [comment]
Fixed in #81 released in 1.7.1
