### ISSUE TITLE
in a build npm

### ISSUE THREAD

**Issue by sarahBuisson** [MicroUtils/kotlin-logging#67]
Hello,
I use your project in my own mpp kotlin lib
I plan to use my lib and your in another app build by npm. (package.json)

Any Idea how I can publish my lib on npm or what i should add to my package.json to use my lib?

Thank-you !

**Comment by oshai** [comment]
Hi,
These two resources might be helpful:
https://www.reddit.com/r/Kotlin/comments/a3mngm/publish_kotlinjs_package_in_npm/
https://medium.com/@chris.barbour03/kotlin-js-building-deploying-and-depending-on-it-with-npm-and-webpack-2f7aab544c9f

**Comment by sarahBuisson** [comment]
@oshai hello, so, i've do a few research...
It would help a lot to use your lib in js if either you publish your lib on npm or if you publish the js build on github with a package.json:
https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly

**Comment by oshai** [comment]
do you have any link on how to do it from gradle?
