### ISSUE TITLE
Any way to (easily) grab an extra copy of the logs?

### ISSUE THREAD

**Issue by salamanders** [MicroUtils/kotlin-logging#69]
Logging works great!  It picks up /resources/simplelogger.properties just fine and prints to console, great ramp-up.

Now I'd like to do something extra with the info+ level logs (write them to a db) Which I assume is a "Handler"  But I started looking into slf4j-simple and Handlers, and wasn't sure where to start.  

Is there an easy way to say "also throw everything at this function, thanks!"

**Comment by oshai** [comment]
Slf4j simple is pretty simple as the name implies. I would suggest to replace it with logback to get such features.

**Comment by salamanders** [comment]
Ok, so nothing to do with kotlin-logging.  drat.  Thank you anyway!
