### ISSUE TITLE
simplify the way how to define logger

### ISSUE THREAD

**Issue by LiYing2010** [MicroUtils/kotlin-logging#77]
Currently, we need the following code to get a instance of logger:

`private val logger = KotlinLogging.logger {} `

the code itself is very simple, but the problem is, we have to put this line in **every class** which use log, and for a large project, there could be many many classes.

So I suggest we can add a new extension property, which can get the logger instance for us, and we can use this property in every classes without calling the logger initialization code.

I made a PR #78 for this, please take a look

**Comment by oshai** [comment]
I have a couple of concerns regarding the suggestion:
- The biggest one is that add a property on all classes clutter your env (ie: it will suggest it for autocompletion in any case you included the library). I really don't like that.
- probably it is better not to have synchrinze block at all (but create duplicated instances).
- I don't think it will work on the file level - only inside classes?

The first one is my main concern preventing me from merging such a PR.

**Comment by LiYing2010** [comment]
>  The biggest one is that add a property on all classes clutter your env (ie: it will suggest it for autocompletion in any case you included the library). I really don't like that for libraries, in your applicative code, it is more acceptable.


no, it will not be added to all classes.
it's an extension property, it will be available only if you import it, like `import mu.log`,
without this explicit import statement, this property will not be added to class.

**Comment by LiYing2010** [comment]
>  probably it is better not to have synchronized block at all (but create duplicated instances).

OK
I think I can remove synchronized block

**Comment by LiYing2010** [comment]
>  I don't think it will work on the file level - only inside classes?

You are right, an extension property only works for classes,
I will do more research, to see if there is anything we can do for the `file level` case

**Comment by oshai** [comment]
Regarding the import, I know it will not added to all classes unless you import. The issue is the IDE will suggest to add it and import on almost any auto-completion (because it's a public extension to all instances)

**Comment by oshai** [comment]
I decided not to merge such a PR at the moment. Thanks anyway!
