### ISSUE TITLE
Everything is disabled

### ISSUE THREAD

**Issue by GitPotTime** [MicroUtils/kotlin-logging#79]
```
val logger = KotlingLogging.logger {}
println("DEBUG: ${logger.isDebugEnabled}")
println("TRACE: ${logger.isTraceEnabled}")
println("INFO: ${logger.isInfoEnabled}")
println("WARN: ${logger.isWarnEnabled}")
println("ERROR: ${logger.isErrorEnabled}")
```

Output: 
```
DEBUG: false
TRACE: false
INFO: false
WARN: false
ERROR: false
```

**Comment by oshai** [comment]
This is an issue with the logging system used. See this note from readme:

**Important note:** kotlin-logging depends on slf4j-api (In the JVM artifact). In runtime, it is also required to depend on a logging implementation. More details in [how-to-configure-slf4j](http://saltnlight5.blogspot.co.il/2013/08/how-to-configure-slf4j-with-different.html). And an excellent detailed explanation in [a-guide-to-logging-in-java](https://www.marcobehler.com/guides/a-guide-to-logging-in-java).
