### ISSUE TITLE
Kotlin-Reflect dependency

### ISSUE THREAD

**Issue by yoavst** [MicroUtils/kotlin-logging#8]
Is there a way to drop the kotlin reflection dependency? a 5 MB library for getting the name of the class from companion sounds too much :)

**Comment by oshai** [comment]
any idea or direction how to do that?

**Comment by oshai** [comment]
one way I think of is checking the name if it ends with "$Companion" and remove it. what do you think?

**Comment by yoavst** [comment]
Since you can name companion this is not 100% working solution, but I believe it is acceptable limitation.

**Comment by oshai** [comment]
A solution for that is to look for the last $ sign. do you think it is better?

**Comment by oshai** [comment]
The removal of kotlin-reflect dependency will be in 1.3.3
