### ISSUE TITLE
move to use dokka for javadocs

### ISSUE THREAD

**Issue by oshai** [MicroUtils/kotlin-logging#82]
seems like docs jars are empty (other than manifest)

**Comment by piyushmor** [comment]
we need to use jcenter() to be able to use dokka. Also, we need to fix our javadoc code blocks to help them be properly formatted.

**Comment by piyushmor** [comment]
also, can you clarify which output format we would use in dokka? html or javadoc?

**Comment by oshai** [comment]
I think javadoc jar.
