### ISSUE TITLE
Supertype of mu.KLogger unresolved (org.slf4j.logger)

### ISSUE THREAD

**Issue by deepakyadav** [MicroUtils/kotlin-logging#83]
Getting following error after upgrading to latest version:
```
Error:Kotlin: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class mu.KLogger, unresolved supertypes: org.slf4j.Logger
```
I think it is cause by following change while migrating to MPP:
```
compile "org.slf4j:slf4j-api:${extra["sl4j_version"]}"
implementation("org.slf4j:slf4j-api:${extra["sl4j_version"]}")
```
Because `mu.KLogger` extends `org.slf4j.Logger`,
we need to use `api` instead of implementation:
`api("org.slf4j:slf4j-api:${extra["sl4j_version"]}")`

**Comment by oshai** [comment]
I think you're right. I will check and fix that.

**Comment by oshai** [comment]
Fixed in 1.7.2. Thanks for reporting!

**Comment by deepakyadav** [comment]
Thanks for quick fix. Please publish the version 1.7.2 as well.

**Comment by oshai** [comment]
Its released. Might take some time to show on maven central.

**Comment by 1951FDG** [comment]
Apparently `io.github.microutils:kotlin-logging:1.12.5` also requires the following,`implementation "org.slf4j:slf4j-api:$slf4j_version"` in the project, for it to compile

**Comment by oshai** [comment]
I plan to deprecate 1.x soon, so I don't plan fixing that. See #180 for details.
