### ISSUE TITLE
logging.exit signature doesn't support ?

### ISSUE THREAD

**Issue by corneil** [MicroUtils/kotlin-logging#84]
The signature for logger.exit should be `override inline fun <T : Any> exit(retval: T?): T?`

**Comment by oshai** [comment]
I think it's true. do you want to contribute that, or should I fix it?

**Comment by corneil** [comment]
I'm busy preparing PR

**Comment by oshai** [comment]
fixed in 1.7.3 and PR #85 Thanks!
