### ISSUE TITLE
Abstract class inheritance convenience 

### ISSUE THREAD

**Issue by ppslim** [MicroUtils/kotlin-logging#91]
Defining a logger as follows is of significant convenience.
```kotlin
protected val LOG = KotlinLogging.logger {}
```

However, when used on abstract classes, we end up with a logger for the abstract class. Whilst this outcome is technically correct, we lose a lot of the convenience that Kotlin offers. Instead we end up with a load of extra boilerplate code in implementations which Kotlin has been so powerful to help reduce.

I can do one of the following in my abstract class already.
```kotlin
protected val LOG = KotlinLogging.logger(this.javaClass.name)
protected val LOG = KotlinLogging.logger(this::class.jvmName)
```

However, it would feel sensible to be able to have KotlinLogging provide a convenience method for the following.

```kotlin
protected val LOG = KotlinLogging.logger(this)
```

This method would also have the benefit of being capable of being used in multi-platform common code.

**Comment by oshai** [comment]
I think this goes against the logging conventions. Usually logger is static and also point to the current file/class so its easier to find where the log message was created and not to inherited class.
