### ISSUE TITLE
fix wiki link to tests

### ISSUE THREAD

**Issue by hennr** [MicroUtils/kotlin-logging#94]
Seems like the link to [tests] in Home.md should point to this now:
https://github.com/MicroUtils/kotlin-logging/tree/master/src/jvmTest/kotlin/mu

I couldn't find a way to edit the wiki or send a PR for this, thus I created this issue.

**Comment by oshai** [comment]
Thanks for reporting it! seems like changing multiplatform structure broke the links. I fixed them in the wiki now.
