### ISSUE TITLE
choose the level of the log

### ISSUE THREAD

**Issue by sarahBuisson** [MicroUtils/kotlin-logging#95]
Hello, I'm currently doing a lib in kotlin, that I want to keep multiplateform (nodejs, browser-js, java)  
I use mu kotlin-logging, but I have an issue : All log are printed in the console on the browser
How can I control the level of what is printed, from the outside of the lib? ( the equivalent of the logback.xml does)

Thank-you !

**Comment by oshai** [comment]
Changing log level for js is done like this: KotlinLoggingConfiguration.LOG_LEVEL = KotlinLoggingConfiguration.DEBUG

See more details here: https://github.com/MicroUtils/kotlin-logging/wiki/Multiplatform-support#js-usage

**Comment by sarahBuisson** [comment]
@oshai 
Thanks for the reactivity ! 
But
There is a typo in the doc, it should be
KotlinLoggingConfiguration.LOG_LEVEL = KotlinLoggingLevel.ERROR;

**Comment by piyushmor** [comment]
can this issue be closed? or is someone adjusting the doc

**Comment by oshai** [comment]
Thanks! I fixed the docs.
