### ISSUE TITLE
Unsure if multiplatform is breaking my basic case or something else

### ISSUE THREAD

**Issue by salamanders** [MicroUtils/kotlin-logging#96]
`io.github.microutils:kotlin-logging:1.6.26` seems to work in my pom.xml
When I recently started a new project, and tried to use the latest version (1.7.6) from 
https://mvnrepository.com/artifact/io.github.microutils/kotlin-logging
The IDE (intellij) couldn't find a place to `import internal val logger = KotlinLogging.logger {}` from. 

I tried also including -common, but still no luck.

Also, in the dependency tree, 
io.github.microutils:kotlin-logging requires both -common and -js?  That seems odd.

Anything I can try to get it to run with the latest version?  Thanks!

**Comment by oshai** [comment]
I am using 1.7.6 without such issue, so try refresh or invalidate caches. Which build system are you using? It might be related.

**Comment by salamanders** [comment]
Intellij to package a jar using maven, then I deploy and run on a rpi with
openjdk 11.

I'll try nuking caches and the .m2 directory.

**Comment by salamanders** [comment]
I had a jar hiding in an unexpected directory that was messing everything up.  My bad!
