### ISSUE TITLE
Upgrade to latest Libraries

### ISSUE THREAD

**Issue by piyushmor** [MicroUtils/kotlin-logging#97]
the current versions and the latest version are different. we can upgrade to these.
|    +--- org.slf4j:slf4j-api:1.7.25 -> 1.7.29
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.41 -> 1.3.50 (*)
|    \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.41 -> 1.3.50

**Comment by oshai** [comment]
PR is welcome!

**Comment by oshai** [comment]
Thanks, I merged it.
